services:
  mydb:
    image: postgres
    container_name: bdd
    ports:
      - "${BDD_PORT}:${BDD_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.28.0.5

  front:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/app/src
      - ../node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - mydb
    environment:
      REACT_PUBLIC_API_URL: ${REACT_PUBLIC_API_URL}
      REACT_PUBLIC_SERVER_PYTHON_URL: ${REACT_PUBLIC_SERVER_PYTHON_URL}
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

  back:
    image: ghcr.io/dockerappsandbox/back:dev
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BACK_PORT: ${BACK_PORT}
    depends_on:
      - mydb
      - front
    networks:
      mynetwork:
        ipv4_address: 172.28.0.2

networks:
  mynetwork:
    external: true

volumes:
  postgres_data:
    driver: local
